kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.ci.name }}
  namespace: {{ .Values.ci.namespace }}
spec:
  selector:
      app: {{ .Values.ci.name }}
      instance: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
